workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 20
    environment:
      java: 17
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
